language: "en"
pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
    case_sensitive: false
  #- name: 'SpellCheckerComponent.CorrectSpelling'
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: RegexEntityExtractor
    use_lookup_tables: True
    use_regexes: True
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
    constrain_similarities: True
  - name: RulePolicy